spring:
  datasource:
    password: "admin"
    username: "admin"
    url: "jdbc:mariadb://localhost:3306/cinema"
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  error:
    include-message: always