spring:
  datasource:
    password: "admin"
    username: "admin"
    url: "jdbc:mariadb://localhost:3306/cinema"
    driver-class-name: "org.mariadb.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect